# Generated by Django 3.0.2 on 2020-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tc',
            field=models.IntegerField(default='1111111111'),
        ),
    ]
