# Generated by Django 3.0.2 on 2020-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tc',
            field=models.IntegerField(default='', verbose_name='tc'),
        ),
    ]
