# Generated by Django 3.0.2 on 2020-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200103_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maas_banka',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maaş Bankası'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profil Foto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='soyad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tc',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tc'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tel'),
        ),
    ]
