# Generated by Django 3.0.2 on 2020-01-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200103_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir'), ('Diğer', 'Diğer')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='kredi_talebi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kredi Talebi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kredi_tutari',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kredi Mevcut'),
        ),
    ]
