# Generated by Django 3.0.2 on 2020-01-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200103_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Adınız'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kredi_tutari',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maaş Aldığınız Bankadaki Kredi Tutarı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maas_banka',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maaş Aldığınız Banka'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='soyad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Soyadınız'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon Mumaranız'),
        ),
    ]
