# Generated by Django 3.0.2 on 2020-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200105_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kredi_tutari',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maaş Aldığı Bankadaki Kredi Tutarı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maas_banka',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maaş Bankası'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='soyad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tel No'),
        ),
    ]
