# Generated by Django 3.0.2 on 2020-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200118_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='userOrangeBlack.svg', upload_to='profile_pics', verbose_name='Profil Foto'),
        ),
    ]
