# Generated by Django 3.0.2 on 2020-01-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200118_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Default_User.png', upload_to='profile_pics', verbose_name='Profil Foto'),
        ),
    ]
