# Generated by Django 3.0.2 on 2020-01-25 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200123_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
        ),
    ]
