# Generated by Django 3.0.2 on 2020-01-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
