# Generated by Django 3.0.2 on 2020-01-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200125_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
