# Generated by Django 3.0.3 on 2020-02-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200207_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tc',
            field=models.IntegerField(blank=True, max_length=11, null=True, unique=True, verbose_name='Tc'),
        ),
    ]
