# Generated by Django 3.0.3 on 2020-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200207_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir'), ('Diğer', 'Diğer')], max_length=20, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kredi_talebi',
            field=models.CharField(blank=True, choices=[('10.000 TL', '10.000 TL'), ('15.000 TL', '15.000 TL'), ('20.000 TL', '20.000 TL'), ('25.000 TL', '25.000 TL'), ('30.000TL', '30.000TL'), ('35.000 TL', '35.000 TL'), ('40.000 TL', '40.000 TL'), ('45.000 TL', '45.000 TL'), ('50.000 TL', '50.000 TL'), ('60.000 TL ve üzeri', '60.000 TL ve üzeri')], max_length=18, null=True, verbose_name='Kredi Talebi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kredi_tutari',
            field=models.CharField(blank=True, choices=[('Yok', 'Yok'), ('5.000 TL', '5.000 TL'), ('10.000 TL', '10.000 TL'), ('15.000 TL', '15.000 TL'), ('20.000 TL', '20.000 TL'), ('25.000 TL', '25.000 TL'), ('30.000TL', '30.000TL'), ('35.000 TL', '35.000 TL'), ('40.000 TL', '40.000 TL'), ('45.000 TL', '45.000 TL'), ('50.000 TL', '50.000 TL'), ('60.000 TL ve üzeri', '60.000 TL ve üzeri')], max_length=18, null=True, verbose_name='Kredi Mevcut'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maas_banka',
            field=models.CharField(blank=True, choices=[('AKBANK', 'AKBANK'), ('AKTİFBANK', 'AKTİFBANK'), ('BURGAN', 'BURGAN'), ('DENİZBANK', 'DENİZBANK'), ('HALK BANKASI', 'HALK BANKASI'), ('GARANTİ BBVA', 'GARANTİ BBVA'), ('HSBC', 'HSBC'), ('ING BANK', 'ING BANK'), ('İŞ BANKASI', 'İŞ BANKASI'), ('ODEA', 'ODEA'), ('VAKIF BANK', 'VAKIF BANK'), ('QNB FİNANSBANK', 'QNB FİNANSBANK'), ('YAPI KREDİ', 'YAPI KREDİ'), ('ZİRAAT BANKASI', 'ZİRAAT BANKASI'), ('DİĞER', 'DİĞER')], max_length=20, null=True, verbose_name='Maaş Bankası'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
